BENCHMARK_CHOICE_DATASET_IDX = 0
SERVER_IPS = ["127.0.0.1", "127.0.0.1", "127.0.0.1"]

BENCHMARK_MEASURE_OFFLINE_COMMU = True
BENCHMARK_MEASURE_ONLINE_COMMU = True
BENCHMARK_MEASURE_ONLINE_COMPUTATION = True

BENCHMARK_CHECK_PROTOCOL_CORRECTNESS = True
# PERFORMANCE_BATCH_SIZE = 2200
# PERFORMANCE_BATCH_SIZE = 1400
PERFORMANCE_BATCH_SIZE = 5000

